include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - throw_in_finally
    - always_declare_return_types
    - avoid_returning_this
    - avoid_unused_constructor_parameters
    - only_throw_errors
    - empty_constructor_bodies
    - eol_at_end_of_file
    - implicit_call_tearoffs
    - avoid_print: true
    - prefer_single_quotes: true

plugins:
  riverpod_lint: ^3.1.3
